name: Portfolio Update and Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:
 
jobs:
  update-data-and-generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run fetch_data.py to populate database
        run: python fetch_data.py

      - name: Run calculations.py to populate database
        run: python calculations.py

      - name: Run report.py to generate report and HTML
        run: python report.py
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html portfolio.db # Add only the files you want to save
          # Use --force-with-lease to resolve the 'rejected' error
          git commit -m "Automated daily report update" || echo "No changes to commit"
          git push --force-with-lease
    
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add index.html portfolio.db
          git commit -m "Automated daily report update" || echo "No changes to commit"
          git push

  deploy-to-github-pages:
    needs: update-data-and-generate-report
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4