name: Mutual Fund Bot Workflow

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight

jobs:
  job1_data_collection:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python file1.py

      - uses: actions/upload-artifact@v4
        with:
          name: mf-database
          path: mf.db

  job2_analysis:
    runs-on: ubuntu-latest
    needs: job1_data_collection
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          name: mf-database
          path: .
      - run: python file2.py
      - uses: actions/upload-artifact@v4
        with:
          name: mf-database-with-metrics
          path: mf.db

  job3_report_generation:
    runs-on: ubuntu-latest
    needs: job2_analysis
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - uses: actions/download-artifact@v4
        with:
          name: mf-database-with-metrics
          path: .
      - run: python file3.py
      - uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: report.html

  deploy:
    runs-on: ubuntu-latest
    needs: job3_report_generation
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Download HTML report artifact
        uses: actions/download-artifact@v4
        with:
          name: html-report
          path: public

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: public
          force_orphan: true
