name: Daily Portfolio Update and Deploy

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *' # Runs at 12:00 AM UTC every day
  workflow_dispatch:
    # Allows for manual trigger

jobs:
  update-data-and-generate-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies from requirements.txt
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run file1.py to populate database
        run: python file1.py

      - name: Run file2.py to populate database
        run: python file2.py

      - name: Run mf_manager.py to generate report and HTML
        run: python mf_manager.py
    
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add .
          git commit -m "Automated daily report update" || echo "No changes to commit"
          git push

  deploy-to-github-pages:
    needs: update-data-and-generate-report
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: main # The branch where your code resides

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: './' # The path to your HTML file and any other assets

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3